export const SITE_URL = "https://china-market-chronicle.vercel.app";
export const SITE_NAME = "中国股市编年史 · History of China Market";
export const SITE_TITLE =
  "中国股市编年史 · History of China Market — A 股 / 港股 百年走势 · 估值 · 回撤";
export const SITE_DESCRIPTION =
  "A 股与港股的历史数据编年史：上证综指、沪深 300、恒生指数等核心指数的年度涨跌、最大回撤、估值变迁、滚动收益与结构指标。" +
  "A long-form chronicle of China's stock market — annual returns, drawdowns, valuation history, " +
  "and structural shifts across Shanghai, Shenzhen, and Hong Kong.";

export const SITE_KEYWORDS: string[] = [
  // 中文 — 指数
  "上证综指",
  "上证综指历史",
  "上证指数",
  "上证指数走势",
  "沪深300",
  "沪深300历史",
  "沪深300走势",
  "沪深300市盈率",
  "沪深300市净率",
  "中证500",
  "创业板指",
  "科创50",
  "恒生指数",
  "恒生指数历史",
  "恒生科技",
  "恒生国企指数",
  // 中文 — 主题
  "A股",
  "A股历史",
  "A股年度涨跌",
  "A股最大回撤",
  "A股估值",
  "A股市盈率",
  "A股市净率",
  "中国股市",
  "中国股市编年史",
  "中国股市历史",
  "中国股市回撤",
  "中国资本市场",
  "中国权益市场",
  "中国股市牛熊",
  "牛市熊市",
  "估值历史",
  "滚动年化收益",
  "回撤分析",
  "波动率历史",
  "股债性价比",
  "港股",
  "港股历史",
  "H股",
  "AH溢价",
  "北向资金",
  "南向资金",
  "沪股通",
  "深股通",
  "港股通",
  "行业市值",
  "行业分布",
  "IPO节奏",
  // English — indices
  "Shanghai Composite",
  "Shanghai Composite Index",
  "Shanghai Composite history",
  "CSI 300",
  "CSI 300 chart",
  "CSI 300 history",
  "CSI 300 PE ratio",
  "CSI 300 PB ratio",
  "CSI 500",
  "ChiNext index",
  "STAR 50",
  "Hang Seng Index",
  "Hang Seng history",
  "Hang Seng Tech",
  "HSCEI",
  // English — themes
  "China stock market",
  "China stock market history",
  "China stock market chronicle",
  "A-share market",
  "A-share history",
  "A-share annual returns",
  "A-share drawdown",
  "A-share valuation",
  "China equity market",
  "Chinese equities",
  "China capital markets",
  "Hong Kong stock market",
  "H-shares",
  "AH premium",
  "Northbound flow",
  "Southbound flow",
  "Stock Connect",
  "rolling returns",
  "max drawdown",
  "realized volatility",
  "equity bond ratio",
  "bull and bear markets China",
  "IPO cadence China",
];
